/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as RealestateRouteImport } from './routes/realestate'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const RealestateRoute = RealestateRouteImport.update({
  id: '/realestate',
  path: '/realestate',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/doctors': typeof DoctorsRoute
  '/favorites': typeof FavoritesRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/realestate': typeof RealestateRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/doctors': typeof DoctorsRoute
  '/favorites': typeof FavoritesRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/realestate': typeof RealestateRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/doctors': typeof DoctorsRoute
  '/favorites': typeof FavoritesRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/realestate': typeof RealestateRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delivery'
    | '/doctors'
    | '/favorites'
    | '/hospitals'
    | '/pharmacies'
    | '/realestate'
    | '/search'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delivery'
    | '/doctors'
    | '/favorites'
    | '/hospitals'
    | '/pharmacies'
    | '/realestate'
    | '/search'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/delivery'
    | '/doctors'
    | '/favorites'
    | '/hospitals'
    | '/pharmacies'
    | '/realestate'
    | '/search'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveryRoute: typeof DeliveryRoute
  DoctorsRoute: typeof DoctorsRoute
  FavoritesRoute: typeof FavoritesRoute
  HospitalsRoute: typeof HospitalsRoute
  PharmaciesRoute: typeof PharmaciesRoute
  RealestateRoute: typeof RealestateRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realestate': {
      id: '/realestate'
      path: '/realestate'
      fullPath: '/realestate'
      preLoaderRoute: typeof RealestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveryRoute: DeliveryRoute,
  DoctorsRoute: DoctorsRoute,
  FavoritesRoute: FavoritesRoute,
  HospitalsRoute: HospitalsRoute,
  PharmaciesRoute: PharmaciesRoute,
  RealestateRoute: RealestateRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
